### PR TITLE
Fixed issue with dynamic arguments in object

### PR DESCRIPTION
**Pull request by suresh-gangumalla**
Resolved issue with dealing dyanmic arguments in an object that has assiged to attribute. 
This issue is mainly occurs with mount, pivot and color attribute when object litteral is assigned as value with dynamic arguments.

- `<Element color="{top: $colorT, bottom: $colorB, left:$colorL} mount="{x: $mX, y: $mY}">`

Code generator now able to correctly link dynamic values for above code snippet. It will output,

`elementConfig1['color'] =  { top: component.colorT, bottom: component.colorB, left: component.colorL}`
`elementConfig1['mount'] =  { x: component.mX, y: component.mY }`

### CODE REVIEW

**Review by michielvandergeest — CHANGES_REQUESTED** [review]
Thanks for making this PR.

While this solution works perfectly, we may be able to improve the code and make it less generic (i.e. without the need to write specifics for mount / color / etc.).

@uguraslan perhaps you can work with Suresh to find a better / smarter regex to handle all cases?

**Comment by suresh-gangumalla** [comment]
@uguraslan  

I have updated key specific regular expressions into a generic expression. 

The generic regular expression is `/\w+\s*:\s*(?:[^\s,}]+|".*?"|'.*?')/g` ,

Sample input object with dynamic values and static value

1. ` "{x: $mX, y: 1}".match(regEx)` results to `['x: $mX', 'y: 1']`
2.  `"{x: $mX, y: $mY}".match(regEx)` results to  `['x: $mX', 'y: $mY']`
3. `"{top: '0xff0000ff', bottom: $colorB, left:$colorL, right: $colorR}"` results to` ["top: '0xff0000ff'", 'bottom: $colorB', 'left:$colorL', 'right: $colorR']`

**Review by uguraslan — APPROVED** [review]
LGTM

**Review by michielvandergeest — CHANGES_REQUESTED** [review]
I think these changes look good.

As this new piece of code handles some specific template use cases, I think it makes sense to add some tests to the generator tests. Please make sure that different cases are covered, also ones where we don't invoke this specific piece of code.

Thanks

**Review by michielvandergeest — APPROVED** [review]
LGTM!

**Pull request merged**
