### PR TITLE
Feature/create app 2

### PR DESCRIPTION
**Pull request by sandeep-vedam**
Added support for creating the Lightning 3 app.

### CODE REVIEW

**Review by michielvandergeest — CHANGES_REQUESTED** [review]
Thanks for the PR so far Sandeep. I've left some comments inline.

I also noticed that when I cancel the creation flow in the middle (ctrl+c) it throws an error instead of gracefully handling it.

**Comment by sandeep-vedam** [comment]
> Thanks for the PR so far Sandeep. I've left some comments inline.
> 
> I also noticed that when I cancel the creation flow in the middle (ctrl+c) it throws an error instead of gracefully handling it.

Hey @michielvandergeest , I have handled this case. Please have a look.

**Review by michielvandergeest — CHANGES_REQUESTED** [review]
While testing I encountered the following issues:

- if I select to _not_ initialize a git repository, the app is created but the flow is hanging
- if I select no to enable eslint (but yes to git) I get an error (`handleErrorFromBinding(ctx); Error: ENOENT: no such file or directory, mkdir`)

**Comment by michielvandergeest** [comment]
Linking to issue #43

**Pull request merged**
